
DROP TRIGGER IF EXISTS "L_ACCOUNTS" ON "L_ACCOUNTS";
DROP TRIGGER IF EXISTS "L_LU_REJECTION_REASON" ON "L_LU_REJECTION_REASON";
DROP TRIGGER IF EXISTS "L_LU_TRANSFER_STATUS" ON "L_LU_TRANSFER_STATUS";
DROP TRIGGER IF EXISTS "L_ENTRIES" ON "L_ENTRIES";
DROP TRIGGER IF EXISTS "L_FULFILLMENTS" ON "L_FULFILLMENTS";
DROP TRIGGER IF EXISTS "L_TRANSFER_ADJUSTMENTS" ON "L_TRANSFER_ADJUSTMENTS";
DROP TRIGGER IF EXISTS "L_TRANSFERS" ON "L_TRANSFERS";

DROP FUNCTION IF EXISTS SYNC_DB_CREATED_DTTM();

DROP TABLE IF EXISTS "L_TRANSFER_ADJUSTMENTS" CASCADE;
DROP TABLE IF EXISTS "L_ACCOUNTS" CASCADE;
DROP TABLE IF EXISTS "L_LU_REJECTION_REASON" CASCADE;
DROP TABLE IF EXISTS "L_LU_TRANSFER_STATUS" CASCADE;
DROP TABLE IF EXISTS "L_ENTRIES" CASCADE;
DROP TABLE IF EXISTS "L_FULFILLMENTS" CASCADE;
DROP TABLE IF EXISTS "L_TRANSFERS" CASCADE;
