CREATE SEQUENCE L_SEQ_ACCOUNT_PK AS INT
  INCREMENT BY 1
  START WITH 1
  CACHE 100
GO

CREATE SEQUENCE L_SEQ_ENTRIES_PK AS INT
  INCREMENT BY 1
  START WITH 1
  CACHE 100
GO

CREATE SEQUENCE L_SEQ_FULFILLMENTS_PK AS INT
  INCREMENT BY 1
  START WITH 1
  CACHE 100
GO

CREATE SEQUENCE L_SEQ_TRANSFERS_PK AS INT
  INCREMENT BY 1
  START WITH 1
  CACHE 100
GO

CREATE SEQUENCE L_SEQ_TRANSFER_ADJUSTMENTS_PK AS INT
  INCREMENT BY 1
  START WITH 1
  CACHE 100
GO

CREATE TABLE [L_ACCOUNTS]
(
  [ACCOUNT_ID] INT NOT NULL CONSTRAINT L_PK_ACCOUNTS PRIMARY KEY,
  [NAME] VARCHAR(255) NOT NULL,
  [BALANCE] NUMERIC(32,16) DEFAULT 0 NOT NULL,
  [CONNECTOR] VARCHAR(1024) NULL,
  [PASSWORD_HASH] VARCHAR(1024) NULL,
  [PUBLIC_KEY] VARCHAR(4000) NULL,
  [IS_ADMIN] SMALLINT DEFAULT 0 NOT NULL,
  [IS_DISABLED] SMALLINT DEFAULT 0 NOT NULL,
  [FINGERPRINT] VARCHAR(255) NULL,
  [MINIMUM_ALLOWED_BALANCE] NUMERIC(32,16) DEFAULT 0 NULL,
  [DB_CREATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_USER] VARCHAR(40) DEFAULT CURRENT_USER NOT NULL
)
GO

CREATE UNIQUE INDEX L_XAK_ACCOUNTS ON [L_ACCOUNTS]
  ([NAME] ASC)
GO

CREATE INDEX L_XIE_FINGERPRINTS ON [L_ACCOUNTS]
  ([FINGERPRINT] ASC)
GO

ALTER TABLE [L_ACCOUNTS] ADD
 DEFAULT next value for L_SEQ_ACCOUNT_PK for [ACCOUNT_ID]
GO

ALTER TABLE [dbo].[L_ACCOUNTS]  WITH NOCHECK ADD  CONSTRAINT [MIN_BALANCE_CONSTRAINT]
  CHECK  (([BALANCE]>=[MINIMUM_ALLOWED_BALANCE]))
GO

ALTER TABLE [dbo].[L_ACCOUNTS] CHECK CONSTRAINT [MIN_BALANCE_CONSTRAINT]
GO


CREATE TABLE [L_LU_REJECTION_REASON] (
  [REJECTION_REASON_ID] INT NOT NULL CONSTRAINT L_PK_TRANSFER_REJECTION_REASON PRIMARY KEY,
  [NAME] VARCHAR(10) NOT NULL,
  [DESCRIPTION] VARCHAR(255) NULL,
  [DB_CREATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_USER] VARCHAR(40) DEFAULT CURRENT_USER NOT NULL
)
GO

CREATE UNIQUE INDEX L_XAK_LU_TRANSFER_REJECTION_REASON ON [L_LU_REJECTION_REASON]
  ([NAME] ASC)
GO

CREATE TABLE [L_LU_TRANSFER_STATUS] (
  [STATUS_ID] INT NOT NULL CONSTRAINT L_PK_TRANSFER_STATUS PRIMARY KEY,
  [NAME] VARCHAR(20) NOT NULL,
  [DESCRIPTION] VARCHAR(255) NULL,
  [DB_CREATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_USER] VARCHAR(40) DEFAULT CURRENT_USER NOT NULL
)
GO

CREATE UNIQUE INDEX L_XAK_LU_TRANSFER_STATUS ON [L_LU_TRANSFER_STATUS]
  ([NAME] ASC)
GO

CREATE TABLE [L_TRANSFERS]
(
  [TRANSFER_ID] INT NOT NULL CONSTRAINT L_PK_TRANSFERS PRIMARY KEY,
  [TRANSFER_UUID] VARCHAR(36) NOT NULL,
  [LEDGER] VARCHAR(1024) NOT NULL,
  [STATUS_ID] INT NULL,
  [REJECTION_REASON_ID] INT NULL,
  [ADDITIONAL_INFO] VARCHAR(4000) NULL,
  [EXECUTION_CONDITION] VARCHAR(4000) NULL,
  [CANCELLATION_CONDITION] VARCHAR(4000) NULL,
  [EXPIRES_DTTM] datetime NULL,
  [PROPOSED_DTTM] datetime NULL,
  [PREPARED_DTTM] datetime NULL,
  [EXECUTED_DTTM] datetime NULL,
  [REJECTED_DTTM] datetime NULL,
  [DB_CREATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_USER] VARCHAR(40) DEFAULT CURRENT_USER NOT NULL
)
GO

CREATE UNIQUE INDEX L_XAK_TRANSFERS ON [L_TRANSFERS]
  ([TRANSFER_UUID] ASC)
GO

ALTER TABLE [L_TRANSFERS] ADD
 DEFAULT next value for L_SEQ_TRANSFERS_PK for [TRANSFER_ID]
GO

CREATE INDEX L_XAK_TRANSFERS_EXECUTION_COND ON [L_TRANSFERS]
  ([EXECUTION_CONDITION] ASC)
GO

ALTER TABLE [L_TRANSFERS] ADD CONSTRAINT FK_REJECTION_REASON_ID__TRANSF
  FOREIGN KEY ([REJECTION_REASON_ID]) REFERENCES [L_LU_REJECTION_REASON]
  ([REJECTION_REASON_ID]) ON DELETE SET NULL
GO
ALTER TABLE [L_TRANSFERS] ADD CONSTRAINT FK_STATUS_ID__TRANSFERS
  FOREIGN KEY ([STATUS_ID]) REFERENCES [L_LU_TRANSFER_STATUS]
  ([STATUS_ID]) ON DELETE SET NULL
GO


CREATE TABLE [L_TRANSFER_ADJUSTMENTS]
(
  [TRANSFER_ADJUSTMENT_ID] INT NOT NULL CONSTRAINT L_PK_TRANSFER_ADJUSTMENTS PRIMARY KEY,
  [TRANSFER_ID] INT NOT NULL,
  [ACCOUNT_ID] INT NOT NULL,
  [DEBIT_CREDIT] VARCHAR(10) NOT NULL,
  [AMOUNT] NUMERIC(32,16) DEFAULT 0 NULL,
  [IS_AUTHORIZED] SMALLINT DEFAULT 0 NOT NULL,
  [MEMO] VARCHAR(4000) NULL,
  [DB_CREATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_USER] VARCHAR(40) DEFAULT CURRENT_USER NOT NULL
)
GO

CREATE UNIQUE INDEX L_XAK_TRANSFER_ADJUSTMENTS ON [L_TRANSFER_ADJUSTMENTS]
  ([TRANSFER_ID] ASC, [ACCOUNT_ID] ASC)
GO

ALTER TABLE [L_TRANSFER_ADJUSTMENTS] ADD
 DEFAULT next value for L_SEQ_TRANSFER_ADJUSTMENTS_PK for [TRANSFER_ADJUSTMENT_ID]
GO

CREATE INDEX L_XIF_TRANSFER_ADJUSTMENTS_TRA ON [L_TRANSFER_ADJUSTMENTS]
  ([TRANSFER_ID] ASC)
GO

CREATE INDEX L_XIF_TRANSFER_ADJUSTMENTS_ACC ON [L_TRANSFER_ADJUSTMENTS]
  ([ACCOUNT_ID] ASC)
GO

CREATE INDEX L_XIE_TRANSFER_ADJUSTMENTS ON [L_TRANSFER_ADJUSTMENTS]
  ([IS_AUTHORIZED] ASC)
GO

ALTER TABLE [L_TRANSFER_ADJUSTMENTS] ADD CONSTRAINT
  FK_TRANSFER_ID__TRANSFER_DETAI FOREIGN KEY ([TRANSFER_ID])
  REFERENCES [L_TRANSFERS] ([TRANSFER_ID])
GO

ALTER TABLE [L_TRANSFER_ADJUSTMENTS] ADD CONSTRAINT
  FK_ACCOUNTS_ID__TRANSFER_DETAI FOREIGN KEY ([ACCOUNT_ID])
  REFERENCES [L_ACCOUNTS] ([ACCOUNT_ID])
GO



CREATE TABLE [L_ENTRIES]
(
  [ENTRY_ID] INT NOT NULL CONSTRAINT L_PK_ENTRIES PRIMARY KEY,
  [TRANSFER_ID] INT NOT NULL,
  [ACCOUNT_ID] INT NOT NULL,
  [CREATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_CREATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_USER] VARCHAR(40) DEFAULT CURRENT_USER NOT NULL
)
GO

ALTER TABLE [L_ENTRIES] ADD
 DEFAULT next value for L_SEQ_ENTRIES_PK for [ENTRY_ID]
GO

CREATE INDEX L_XIF_ENTRIES_ACCOUNT ON [L_ENTRIES]
  ([ACCOUNT_ID] ASC)
GO

CREATE INDEX L_XIF_ENTRIES_TRANSFER ON [L_ENTRIES]
  ([TRANSFER_ID] ASC)
GO

CREATE INDEX L_XIE_ENTRIES ON [L_ENTRIES]
  ([CREATED_DTTM] ASC)
GO

ALTER TABLE [L_ENTRIES] ADD CONSTRAINT FK_ACCOUNT_ID__ENTRIES FOREIGN KEY
  ([ACCOUNT_ID]) REFERENCES [L_ACCOUNTS] ([ACCOUNT_ID])
GO

ALTER TABLE [L_ENTRIES] ADD CONSTRAINT FK_TRANSFER_ID__ENTRIES FOREIGN KEY
  ([TRANSFER_ID]) REFERENCES [L_TRANSFERS] ([TRANSFER_ID])
GO


CREATE TABLE [L_FULFILLMENTS]
(
  [FULFILLMENT_ID] INT NOT NULL CONSTRAINT L_PK_FULFILLMENTS PRIMARY KEY,
  [TRANSFER_ID] INT NOT NULL,
  [CONDITION_FULFILLMENT] VARCHAR(4000) NULL,
  [DB_CREATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_DTTM] datetime DEFAULT getdate() NOT NULL,
  [DB_UPDATED_USER] VARCHAR(40) DEFAULT CURRENT_USER NOT NULL
)
GO

ALTER TABLE [L_FULFILLMENTS] ADD
 DEFAULT next value for L_SEQ_ENTRIES_PK for [FULFILLMENT_ID]
GO

ALTER TABLE [L_FULFILLMENTS] ADD CONSTRAINT FK_TRANSFER_ID__TRANSFERS
  FOREIGN KEY ([TRANSFER_ID]) REFERENCES [L_TRANSFERS] ([TRANSFER_ID])
GO



INSERT INTO [L_LU_REJECTION_REASON] ([REJECTION_REASON_ID], [NAME], [DESCRIPTION])
  VALUES (0, 'cancelled', 'The transfer was cancelled');
INSERT INTO [L_LU_REJECTION_REASON] ([REJECTION_REASON_ID], [NAME], [DESCRIPTION])
  VALUES (1, 'expired', 'The transfer expired automatically');
INSERT INTO [L_LU_TRANSFER_STATUS] ([STATUS_ID], [NAME]) VALUES (0, 'proposed');
INSERT INTO [L_LU_TRANSFER_STATUS] ([STATUS_ID], [NAME]) VALUES (1, 'prepared');
INSERT INTO [L_LU_TRANSFER_STATUS] ([STATUS_ID], [NAME]) VALUES (2, 'executed');
INSERT INTO [L_LU_TRANSFER_STATUS] ([STATUS_ID], [NAME]) VALUES (3, 'rejected');

