
IF OBJECT_ID('dbo.[FK_ACCOUNTS_ID__TRANSFER_DETAI]', 'F') IS NOT NULL
  ALTER TABLE [L_TRANSFER_ADJUSTMENTS] DROP CONSTRAINT FK_ACCOUNTS_ID__TRANSFER_DETAI
GO

IF OBJECT_ID('dbo.[FK_TRANSFER_ID__TRANSFER_DETAI]', 'F') IS NOT NULL
  ALTER TABLE [L_TRANSFER_ADJUSTMENTS] DROP CONSTRAINT FK_TRANSFER_ID__TRANSFER_DETAI
GO

IF OBJECT_ID('dbo.[FK_TRANSFER_ID__TRANSFERS]', 'F') IS NOT NULL
  ALTER TABLE [L_FULFILLMENTS] DROP CONSTRAINT FK_TRANSFER_ID__TRANSFERS
GO

IF OBJECT_ID('dbo.[FK_ACCOUNT_ID__ENTRIES]', 'F') IS NOT NULL
  ALTER TABLE [L_ENTRIES] DROP CONSTRAINT FK_ACCOUNT_ID__ENTRIES
GO

IF OBJECT_ID('dbo.[FK_TRANSFER_ID__ENTRIES]', 'F') IS NOT NULL
  ALTER TABLE [L_ENTRIES] DROP CONSTRAINT FK_TRANSFER_ID__ENTRIES
GO

IF OBJECT_ID('dbo.[FK_REJECTION_REASON_ID__TRANSF]', 'F') IS NOT NULL
  ALTER TABLE [L_TRANSFERS] DROP CONSTRAINT FK_REJECTION_REASON_ID__TRANSF
GO

IF OBJECT_ID('dbo.[FK_STATUS_ID__TRANSFERS]', 'F') IS NOT NULL
  ALTER TABLE [L_TRANSFERS] DROP CONSTRAINT FK_STATUS_ID__TRANSFERS
GO


IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'L_TRANSFER_ADJUSTMENTS'))
BEGIN
    DROP TABLE [L_TRANSFER_ADJUSTMENTS]
END
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'L_ENTRIES'))
BEGIN
    DROP TABLE [L_ENTRIES]

END
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'L_FULFILLMENTS'))
BEGIN
    DROP TABLE [L_FULFILLMENTS]
END
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'L_LU_REJECTION_REASON'))
BEGIN
    DROP TABLE [L_LU_REJECTION_REASON]

END
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'L_LU_TRANSFER_STATUS'))
BEGIN
    DROP TABLE [L_LU_TRANSFER_STATUS]

END
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'L_TRANSFERS'))
BEGIN
    DROP TABLE [L_TRANSFERS]

END
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'L_ACCOUNTS'))
BEGIN
    DROP TABLE [L_ACCOUNTS]

END
GO






IF (EXISTS (SELECT SEQUENCE_NAME FROM INFORMATION_SCHEMA.SEQUENCES
            WHERE SEQUENCE_NAME = 'L_SEQ_TRANSFER_ADJUSTMENTS_PK'))
BEGIN
    DROP SEQUENCE L_SEQ_TRANSFER_ADJUSTMENTS_PK
END
GO


IF (EXISTS (SELECT SEQUENCE_NAME FROM INFORMATION_SCHEMA.SEQUENCES
            WHERE SEQUENCE_NAME = 'L_SEQ_ACCOUNT_PK'))
BEGIN
    DROP SEQUENCE L_SEQ_ACCOUNT_PK
END
GO



IF (EXISTS (SELECT SEQUENCE_NAME FROM INFORMATION_SCHEMA.SEQUENCES
            WHERE SEQUENCE_NAME = 'L_SEQ_ENTRIES_PK'))
BEGIN
    DROP SEQUENCE L_SEQ_ENTRIES_PK
END
GO



IF (EXISTS (SELECT SEQUENCE_NAME FROM INFORMATION_SCHEMA.SEQUENCES
            WHERE SEQUENCE_NAME = 'L_SEQ_FULFILLMENTS_PK'))
BEGIN
    DROP SEQUENCE L_SEQ_FULFILLMENTS_PK
END
GO



IF (EXISTS (SELECT SEQUENCE_NAME FROM INFORMATION_SCHEMA.SEQUENCES
            WHERE SEQUENCE_NAME = 'L_SEQ_TRANSFERS_PK'))
BEGIN
    DROP SEQUENCE L_SEQ_TRANSFERS_PK
END
GO



IF (EXISTS (SELECT SEQUENCE_NAME FROM INFORMATION_SCHEMA.SEQUENCES
            WHERE SEQUENCE_NAME = 'L_SEQ_TRANSFER_ADJUSTMENTS_PK'))
BEGIN
    DROP SEQUENCE L_SEQ_TRANSFER_ADJUSTMENTS_PK
END
GO

