
ALTER TABLE [L_TRANSFERS] DROP CONSTRAINT FK_REJECTION_REASON_ID__TRANSF
GO
ALTER TABLE [L_TRANSFERS] DROP CONSTRAINT FK_STATUS_ID__TRANSFERS
GO
ALTER TABLE [L_TRANSFER_ADJUSTMENTS] DROP CONSTRAINT FK_TRANSFER_ID__TRANSFER_DETAI
GO
ALTER TABLE [L_TRANSFER_ADJUSTMENTS] DROP CONSTRAINT FK_ACCOUNTS_ID__TRANSFER_DETAI
GO
ALTER TABLE [L_ENTRIES] DROP CONSTRAINT FK_ACCOUNT_ID__ENTRIES
GO
ALTER TABLE [L_ENTRIES] DROP CONSTRAINT FK_TRANSFER_ID__ENTRIES
GO
ALTER TABLE [L_FULFILLMENTS] DROP CONSTRAINT FK_TRANSFER_ID__TRANSFERS
GO

TRUNCATE TABLE [L_TRANSFER_ADJUSTMENTS]
GO
TRUNCATE TABLE [L_ACCOUNTS]
GO
TRUNCATE TABLE [L_FULFILLMENTS]
GO
TRUNCATE TABLE [L_ENTRIES]
GO
TRUNCATE TABLE [L_TRANSFERS]
GO

ALTER TABLE [L_TRANSFERS] ADD CONSTRAINT FK_REJECTION_REASON_ID__TRANSF
  FOREIGN KEY ([REJECTION_REASON_ID]) REFERENCES [L_LU_REJECTION_REASON]
  ([REJECTION_REASON_ID]) ON DELETE SET NULL
GO
ALTER TABLE [L_TRANSFERS] ADD CONSTRAINT FK_STATUS_ID__TRANSFERS
  FOREIGN KEY ([STATUS_ID]) REFERENCES [L_LU_TRANSFER_STATUS]
  ([STATUS_ID]) ON DELETE SET NULL
GO
ALTER TABLE [L_TRANSFER_ADJUSTMENTS] ADD CONSTRAINT
  FK_TRANSFER_ID__TRANSFER_DETAI FOREIGN KEY ([TRANSFER_ID])
  REFERENCES [L_TRANSFERS] ([TRANSFER_ID])
GO
ALTER TABLE [L_TRANSFER_ADJUSTMENTS] ADD CONSTRAINT
  FK_ACCOUNTS_ID__TRANSFER_DETAI FOREIGN KEY ([ACCOUNT_ID])
  REFERENCES [L_ACCOUNTS] ([ACCOUNT_ID])
GO
ALTER TABLE [L_ENTRIES] ADD CONSTRAINT FK_ACCOUNT_ID__ENTRIES FOREIGN KEY
  ([ACCOUNT_ID]) REFERENCES [L_ACCOUNTS] ([ACCOUNT_ID])
GO
ALTER TABLE [L_ENTRIES] ADD CONSTRAINT FK_TRANSFER_ID__ENTRIES FOREIGN KEY
  ([TRANSFER_ID]) REFERENCES [L_TRANSFERS] ([TRANSFER_ID])
GO
ALTER TABLE [L_FULFILLMENTS] ADD CONSTRAINT FK_TRANSFER_ID__TRANSFERS
  FOREIGN KEY ([TRANSFER_ID]) REFERENCES [L_TRANSFERS] ([TRANSFER_ID])
GO
