BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "L_ACCOUNTS"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "L_SUBSCRIPTIONS"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "L_ENTRIES"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "L_TRANSFERS"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "L_FULFILLMENTS"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "L_NOTIFICATIONS"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE L_SEQ_ACCOUNT_PK';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE L_SEQ_ENTRIES_PK';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE L_SEQ_FULFILLMENTS_PK';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -2289 THEN
    RAISE;
  END IF;
END;
/

CREATE SEQUENCE L_SEQ_ACCOUNT_PK
  INCREMENT BY 1
  START WITH 1
  NOCYCLE
  CACHE 100
  ORDER
/

CREATE SEQUENCE L_SEQ_ENTRIES_PK
  INCREMENT BY 1
  START WITH 1
  NOCYCLE
  CACHE 100
  ORDER
/

CREATE SEQUENCE L_SEQ_FULFILLMENTS_PK
  INCREMENT BY 1
  START WITH 1
  NOCYCLE
  CACHE 100
  ORDER
/

CREATE TABLE "L_ACCOUNTS"
(
  "ACCOUNT_ID"           INTEGER NOT NULL ,
  "NAME"                 VARCHAR2(255) NOT NULL ,
  "BALANCE"              NUMBER(32,16) NULL ,
  "CONNECTOR"            VARCHAR2(1024) NULL ,
  "PASSWORD_HASH"        VARCHAR2(1024) NULL ,
  "PUBLIC_KEY"           VARCHAR2(4000) NULL ,
  "IS_ADMIN"             SMALLINT NULL ,
  "IS_DISABLED"          SMALLINT NULL ,
  "FINGERPRINT"          VARCHAR2(255) ,
  "MINIMUM_ALLOWED_BALANCE" NUMBER(32,16) DEFAULT  0  NULL,
  CONSTRAINT "MIN_BALANCE_CONSTRAINT" CHECK ("BALANCE" >= "MINIMUM_ALLOWED_BALANCE")
)
/

CREATE INDEX L_XPK_ACCOUNTS ON "L_ACCOUNTS"
  ("ACCOUNT_ID" ASC)
/

ALTER TABLE "L_ACCOUNTS" ADD CONSTRAINT L_PK_ACCOUNTS PRIMARY KEY
  ("ACCOUNT_ID")
/

CREATE UNIQUE INDEX L_XAK_ACCOUNTS ON "L_ACCOUNTS"
  ("NAME" ASC)
/

ALTER TABLE "L_ACCOUNTS" ADD CONSTRAINT L_XAK_ACCOUNTS UNIQUE
  ("NAME")
/

CREATE INDEX L_XIE_FINGERPRINTS ON "L_ACCOUNTS"
  ("FINGERPRINT" ASC)
/


CREATE TABLE "L_SUBSCRIPTIONS"
(
  "SUBSCRIPTION_ID"      VARCHAR2(64) NOT NULL ,
  "OWNER"                VARCHAR2(1024) NULL ,
  "EVENT"                VARCHAR2(255) DEFAULT NULL NULL ,
  "SUBJECT"              VARCHAR2(1024) NULL ,
  "TARGET"               VARCHAR2(1024) DEFAULT NULL NULL ,
  "IS_DELETED"           SMALLINT DEFAULT 0 NOT NULL
)
/

CREATE INDEX L_XPK_SUBSCRIPTIONS ON "L_SUBSCRIPTIONS"
  ("SUBSCRIPTION_ID" ASC)
/

ALTER TABLE "L_SUBSCRIPTIONS" ADD CONSTRAINT L_PK_SUBSCRIPTIONS PRIMARY KEY
  ("SUBSCRIPTION_ID")
/

CREATE INDEX L_XIE_SUBSCRIPTIONS ON "L_SUBSCRIPTIONS"
  ("IS_DELETED" ASC)
/

CREATE TABLE "L_LU_REJECTION_REASON" (
  "REJECTION_REASON_ID"   INTEGER NOT NULL,
  "NAME"                  CHARACTER VARYING(10) NOT NULL,
  "DESCRIPTION"           CHARACTER VARYING(255) NULL
);
/

CREATE INDEX "L_XPK_LU_TRANSFERS_REJECTION_R" ON "L_LU_REJECTION_REASON"
  ("REJECTION_REASON_ID" ASC);
/
ALTER TABLE "L_LU_REJECTION_REASON" ADD CONSTRAINT
  "L_PK_LU_TRANSFERS_REJECTION_RE"
  PRIMARY KEY ("REJECTION_REASON_ID");
/
CREATE INDEX "L_XAK_LU_TRANSFERS_REJECTION_R" ON "L_LU_REJECTION_REASON"
  ("NAME" ASC);
/
ALTER TABLE "L_LU_REJECTION_REASON" ADD CONSTRAINT
  "L_AK_LU_TRANSFERS_REJECTION_RE" UNIQUE
  ("NAME");
/


CREATE TABLE "L_TRANSFERS"
(
  "TRANSFER_ID"            VARCHAR2(36) NOT NULL ,
  "LEDGER"                 VARCHAR2(1024) NULL ,
  "DEBITS"                 VARCHAR2(4000) NULL ,
  "CREDITS"                VARCHAR2(4000) NULL ,
  "STATE"                  VARCHAR2(4000) NULL ,
  "REJECTION_REASON_ID"    INTEGER NULL ,
  "ADDITIONAL_INFO"        VARCHAR2(4000) NULL ,
  "EXECUTION_CONDITION"    VARCHAR2(4000) NULL ,
  "CANCELLATION_CONDITION" VARCHAR2(4000) NULL ,
  "EXPIRES_AT"             TIMESTAMP NULL ,
  "PROPOSED_AT"            TIMESTAMP NULL ,
  "PREPARED_AT"            TIMESTAMP NULL ,
  "EXECUTED_AT"            TIMESTAMP NULL ,
  "REJECTED_AT"            TIMESTAMP NULL
)
/

CREATE INDEX L_XPK_TRANSFERS ON "L_TRANSFERS"
  ("TRANSFER_ID" ASC)
/

ALTER TABLE "L_TRANSFERS" ADD CONSTRAINT L_PK_TRANSFERS PRIMARY KEY
  ("TRANSFER_ID")
/

ALTER TABLE "L_TRANSFERS" ADD (CONSTRAINT "FK_REJECTION_REASON_ID__TRANSF"
  FOREIGN KEY ("REJECTION_REASON_ID") REFERENCES "L_LU_REJECTION_REASON"
  ("REJECTION_REASON_ID") ON DELETE SET NULL);
/

CREATE TABLE "L_ENTRIES"
(
  "ENTRY_ID"             INTEGER  NOT NULL ,
  "TRANSFER_ID"          VARCHAR2(64) NULL ,
  "ACCOUNT"              INTEGER NULL ,
  "CREATED_AT"           TIMESTAMP NOT NULL
)
/

CREATE INDEX L_XPK_ENTRIES ON "L_ENTRIES"
  ("ENTRY_ID" ASC)
/

ALTER TABLE "L_ENTRIES" ADD CONSTRAINT L_PK_ENTRIES PRIMARY KEY
  ("ENTRY_ID")
/

CREATE INDEX L_XAK_ENTRIES ON "L_ENTRIES"
  ("TRANSFER_ID" ASC, "ACCOUNT" ASC)
/

CREATE INDEX L_XIF_ENTRIES_ACCOUNT ON "L_ENTRIES"
  ("ACCOUNT" ASC)
/

CREATE INDEX L_XIF_ENTRIES_TRANSFER ON "L_ENTRIES"
  ("TRANSFER_ID" ASC)
/

CREATE INDEX L_XIE_ENTRIES ON "L_ENTRIES"
  ("CREATED_AT" ASC)
/

CREATE TABLE "L_FULFILLMENTS"
(
  "FULFILLMENT_ID"        INTEGER NOT NULL ,
  "TRANSFER_ID"           VARCHAR2(64) NULL ,
  "CONDITION_FULFILLMENT" VARCHAR2(4000) NULL
)
/

CREATE INDEX L_XPK_FULFILLMENTS ON "L_FULFILLMENTS"
  ("FULFILLMENT_ID" ASC)
/

ALTER TABLE "L_FULFILLMENTS" ADD CONSTRAINT L_PK_FULFILLMENTS PRIMARY KEY
  ("FULFILLMENT_ID")
/

CREATE INDEX L_XIF_FULFILLMENTS ON "L_FULFILLMENTS"
  ("TRANSFER_ID" ASC)
/

CREATE TABLE "L_NOTIFICATIONS"
(
  "NOTIFICATION_ID"      VARCHAR2(36) NOT NULL ,
  "SUBSCRIPTION_ID"      VARCHAR2(36) NULL ,
  "TRANSFER_ID"          VARCHAR2(36) NULL ,
  "RETRY_COUNT"          INTEGER DEFAULT 0 NULL ,
  "RETRY_AT"             TIMESTAMP WITH TIME ZONE
)
/

CREATE INDEX XPKL_NOTIFICATIONS ON "L_NOTIFICATIONS"
  ("NOTIFICATION_ID" ASC)
/

ALTER TABLE "L_NOTIFICATIONS" ADD CONSTRAINT L_PK_NOTIFICATIONS PRIMARY KEY
  ("NOTIFICATION_ID")
/

CREATE INDEX L_XIE_NOTIFICATIONS_RETRY_AT ON "L_NOTIFICATIONS"
  ("RETRY_AT" ASC)
/

CREATE INDEX L_XIF_NOTIFICATIONS_SUB ON "L_NOTIFICATIONS"
  ("SUBSCRIPTION_ID" ASC)
/

CREATE INDEX L_XIF_NOTIFICATIONS_TRANSFER ON "L_NOTIFICATIONS"
  ("TRANSFER_ID" ASC)
/

CREATE OR REPLACE TRIGGER L_TRG_ACCOUNTS_SEQ
  BEFORE INSERT
  ON "L_ACCOUNTS"
  FOR EACH ROW
  WHEN (new."ACCOUNT_ID" is null)
DECLARE
  v_id "L_ACCOUNTS"."ACCOUNT_ID"%TYPE;
BEGIN
  SELECT L_SEQ_ACCOUNT_PK.nextval INTO v_id FROM DUAL;
  :new."ACCOUNT_ID" := v_id;
END L_TRG_ACCOUNTS_SEQ;
/

CREATE OR REPLACE TRIGGER L_TRG_ENTRIES_SEQ
  BEFORE INSERT
  ON "L_ENTRIES"
  FOR EACH ROW
  WHEN (new."ENTRY_ID" is null)
DECLARE
  v_id "L_ENTRIES"."ENTRY_ID"%TYPE;
BEGIN
  SELECT L_SEQ_ENTRIES_PK.nextval INTO v_id FROM DUAL;
  :new."ENTRY_ID" := v_id;
END L_TRG_ENTRIES_SEQ;
/

CREATE OR REPLACE TRIGGER L_TRG_FULFILLMENTS_SEQ
  BEFORE INSERT
  ON "L_FULFILLMENTS"
  FOR EACH ROW
  WHEN (new."FULFILLMENT_ID" is null)
DECLARE
  v_id "L_FULFILLMENTS"."FULFILLMENT_ID"%TYPE;
BEGIN
  SELECT L_SEQ_FULFILLMENTS_PK.nextval INTO v_id FROM DUAL;
  :new."FULFILLMENT_ID" := v_id;
END L_TRG_FULFILLMENTS_SEQ;
/


CREATE OR REPLACE TRIGGER L_TRG_ENTRIES_INS
BEFORE INSERT
   ON  "L_ENTRIES"
   FOR EACH ROW
BEGIN
   :new."CREATED_AT" := sysdate;
END;
/

INSERT INTO "L_LU_REJECTION_REASON" ("REJECTION_REASON_ID", "NAME", "DESCRIPTION")
  VALUES (0, 'cancelled', 'The transfer was cancelled');
INSERT INTO "L_LU_REJECTION_REASON" ("REJECTION_REASON_ID", "NAME", "DESCRIPTION")
  VALUES (1, 'expired', 'The transfer expired automatically');

exit
