DROP TABLE "L_ACCOUNTS";
DROP TABLE "fulfillments";
DROP TABLE "entries";
DROP TABLE "L_NOTIFICATIONS";
DROP TABLE "L_SUBSCRIPTIONS";
DROP TABLE "L_TRANSFERS";
DROP TABLE "migrations";
DROP TABLE "migrations_lock";
